development:
  cloud_name: wade712vn
  api_key: '588575815354927'
  api_secret: MbsA3pkan_0G2g0Oj_Y5mFWR3EM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: wade712vn
  api_key: '588575815354927'
  api_secret: MbsA3pkan_0G2g0Oj_Y5mFWR3EM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: wade712vn
  api_key: '588575815354927'
  api_secret: MbsA3pkan_0G2g0Oj_Y5mFWR3EM
  enhance_image_tag: true
  static_image_support: false


